export default {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  // Authentication
  MISSING_AUTHORIZATION: 'MISSING_AUTHORIZATION',
  INVALID_AUTHORIZATION: 'INVALID_AUTHORIZATION',
  INVALID_AUTHORIZATION_TYPE: 'INVALID_AUTHORIZATION_TYPE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  // Permissions
  NOT_ENOUGH_PRIVILEGES: 'NOT_ENOUGH_PRIVILEGES',
  // User
  USER_FETCH_ERROR: 'USER_FETCH_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EXISTS: 'USER_EXISTS',
  // Validation
  INVALID_BODY: 'INVALID_BODY'
}
